### ISSUE TITLE
EAS, EMB 플러그인을 기본으로 활성화

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#1196]
확장팩으로 배포할 경우, 스팸 차단을 위한 EAS/EMB 플러그인을 처음 설치할 때 기본으로 활성화하도록 하는 것을 제안합니다. EMB의 경우 현재는 확장팩에 들어있지 않지만 넣는 것이 좋을 것 같습니다.

<ul><li>이슈 등록시간: 2009-01-18T02:01:37</li>
<li>마지막 수정시간: 2009-03-05T17:28:04</li></ul>

<table class="trac-migrated-comments">
<tr><th style="text-align:left">Comment 1 by inureyes at 2009-03-05T17:28:04</th></tr>
<tr><td>
지금은 EAS를 전역 설정하는 방법 등이 없습니다. (전역 플러그인등이 없죠) 해당 기능을 추가해야 할 것 같습니다.
</td></tr>
</table>

**Comment by inureyes** [comment]
Will handle with bundle issue
