### ISSUE TITLE
관리 패널에서 댓글 줄여보기 목록 기능

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#1308]
# 개요 
* 관리 패널에서 댓글을 한 줄로 줄여서 보는 기능을 추가합니다.
* 스패밍 쥐쥐

<ul><li>이슈 등록시간: 2009-07-28T16:51:08</li>
<li>마지막 수정시간: 2009-07-28T16:51:19</li></ul>

<table class="trac-migrated-comments">
</table>

**Comment by inureyes** [comment]
Fixed at #1682
