### ISSUE TITLE
minicube를 만든다.

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#1490]
스킨호환성을 유지하는
textcube의 light version을 만든다.

최소 400req/s 이상을 유지할 수 있도록 만든다.

<ul><li>이슈 등록시간: 2010-08-12T02:19:03</li>
<li>마지막 수정시간: 2010-08-19T21:44:26</li></ul>

<table class="trac-migrated-comments">
<tr><th style="text-align:left">Comment 1 by inureyes at 2010-08-19T21:44:26</th></tr>
<tr><td>
## What to prune : 
* Reader function
* Random tags
* Multi-user support
* Plugin function (change to light version)
</td></tr>
</table>

**Comment by inureyes** [comment]
해당 변경 사항들은 1.9 브렌치에 적용되었음.
