### ISSUE TITLE
블로그 첫 페이지 설정

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#1527]
블로그 첫 페이지블로그 첫 페이지에서 최근 글을 보여주도록 합니다.[[BR]]블로그 첫 페이지에서 표지를 보여주도록 합니다.[[BR]]블로그 첫 페이지에서 라인을 보여주도록 합니다.

표지나, 라인을 지원하지 않는 스킨을 사용중인 경우
최근글이 아닌 표지나, 라인을 우선순위로 설정시 백지만을 보여주게 되므로 이를 우회할 방법이 필요함

<ul><li>이슈 등록시간: 2010-11-11T13:49:57</li>
<li>마지막 수정시간: 2010-11-11T13:49:57</li></ul>

<table class="trac-migrated-comments">
</table>

**Comment by inureyes** [comment]
It's intended. ( https://github.com/Needlworks/Textcube/blob/master/interface/index.php#L92 )
