### ISSUE TITLE
자동 로그인 기능

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#1536]
# 개요 
* 자동 로그인 기능을 추가합니다.

<ul><li>이슈 등록시간: 2010-12-24T01:19:36</li>
<li>마지막 수정시간: 2011-10-18T15:10:55.015106</li></ul>

<table class="trac-migrated-comments">
<tr><th style="text-align:left">Comment 1 by inureyes at 2010-12-24T01:34:41</th></tr>
<tr><td>
현재는 매번 세션 타임 비교로 세션을 destroy함 -> 구조를 바꾸어서 destroy time을 저장하도록 함.
</td></tr>
<tr><th style="text-align:left">Comment 2 by inureyes at 2010-12-24T01:44:12</th></tr>
<tr><td>
4ab66f03871330d3529fc950eb972a3f19b1ce48

refs #1536
* Field added for auto-login
</td></tr>
<tr><th style="text-align:left">Comment 3 by inureyes at 2010-12-24T02:19:02</th></tr>
<tr><td>
8a697550f500f2383eb5a5d16a2dd9173163bac4

refs #1536
* Convert original session handlers to permanant-login compatible
* TODO
* Add permanent login selection UI
* Allow session handler to use permanent login
* modify memcache handler
</td></tr>
<tr><th style="text-align:left">Comment 4 by inureyes at 2011-10-18T15:10:55.015106</th></tr>
<tr><td>
In 213bff7eb2c482e5642089d1e2e60cd6f410c7a8
:
    
    #!CommitTicketReference repository="" revision="779573d7e302d6ca7551bc76a788df197c955695"
    refs #1300, #1536 : Modified : set permanent login selection UI
    * Human-readable period method.
    
</td></tr>
</table>

**Comment by inureyes** [comment]
TODO : add config setting on control panel.
