### ISSUE TITLE
SSL 지원

### ISSUE THREAD

**Issue by LI-NA** [Needlworks/Textcube#1669]
코드를 보면 전체적으로 강제 http:// 삽입을 합니다.
이를 유동적으로 https 로 바꿀 수 있으면 좋겠습니다.

지금은 common2.js 에서 src="" 를 치환하는 부분을 https://로 수정,
rewrite.php에서 PHP 출력 버퍼를 이용해 모든 http://를 https://로 치환해서 사용하고 있습니다.

이러한 방법은 어떤 버그를 유발할지 모르니, 빠른 시일 내로 SSL도 지원해주셨으면 합니다.

**Comment by inureyes** [comment]
TODO 
 - Add useSSL=true option to config.php when init setup uses https protocol.
