### ISSUE TITLE
마지막 페이지 페이징 버그 문제

### ISSUE THREAD

**Issue by waltererz** [Needlworks/Textcube#1683]
페이징 관련하여 버그를 발견하여 등록합니다.

카테고리 목록 보기 중의 페이징은 문제가 없으나,

글 보기 중 페이징에 문제가 있습니다.

마지막 글 보기 링크가 첫 번째 글이 아닌 해당 페이징 그룹의 마지막 글로 연결됩니다.

예를 들어,

« 1 ... 9 10 11 12 13 14 15 16 17 ... 89 »

이렇게 되어 있는 경우,

89는 첫 번째 글로 연결되어야 하지만, 17번 페이지의 글로 연결됩니다.

첫 번째 글이 textcube.com/1 이고, 17번 페이지의 글이 textcube.com/70 이라면,

마지막 페이지 페이징 링크를 클릭하는 경우 textcube.com/1 이 아닌 textcube.com/70 으로 연결됩니다.

**Comment by inureyes** [comment]
@zvuc @waltererz 혹시 괜찮으시다면 지금 사용하시는 스킨의 <paging> 안에 든 부분을 여기 붙여주실 수 있을까요? 제 테스트 사이트에선 현상이 일어나지 않아서, 스킨과 연계해서 고민해 보려고 합니다. (제 블로그의 경우 http://forest.nubimaru.com/entry/brain-evolution-and-media 가 예시가 될텐데, 혹시 제 블로그에서도 같은 현상을 재현할 수가 있을까요?)

**Comment by inureyes** [comment]
@zvuc @waltererz 확인했습니다. 문자 주소를 쓸 경우엔 발생하지 않고, 숫자 주소를 쓸 경우에만 나타나는 현상이네요. 재밌네요. ㅎㅎ

**Comment by inureyes** [comment]
수정했습니다 .테스트 부탁 드립니다. :+1:
