### ISSUE TITLE
Let XHTML Go

### ISSUE THREAD

**Issue by inureyes** [Needlworks/Textcube#1717]
Summary
=======

Let XHTML go, let XHTML go!
Can't hold it back any more.
Let XHTML go, let XHTML go!
Turn away and slam the door.
I don't care what they're going to say.
Let the storm rage on.
The IE6/7 never bothered me anyway.

 * Change default DOM from XHTML1 to HTML5

**Comment by misol** [comment]
Let it go~ Let it go~
