### ISSUE TITLE
두 가지 문제점

### ISSUE THREAD

**Issue by pat-al** [Needlworks/Textcube#1726]
오랜 만에 새 판으로 판올림했는데, 여러 모로 아주 만족스럽고 모바일 스킨이 매우 마음에 듭니다.
문제점이 좀 있는데 고쳐 주셨으면 합니다.

1.10.1 베타2판을 써 보았는데, 덧글을 넣으려고 하면 이름 또는 본문을 넣으라는 말이 나와서 덧글을 넣을 수 없습니다. 그래서 1.10판으로 다시 돌아왔습니다. 지금 텍스트큐브의 공지 블로그도 같은 문제가 생기고 있어서 그 곳에 덧글을 남기지 못하고 이 곳에 글을 쓰고 있습니다.

펼기기/접기(more/less) 객체가 들어간 글은 웹 화면에 아무것도 전혀 뜨지 않습니다.
기본 스킨에 플러그인을 거의 쓰지 않는 상태에서 해 보아도 같습니다.

**Comment by achimnol** [comment]
more/less 기능은 저도 같은 증상 있었는데 이제 잘 동작하는 것 확인했습니다.
