### ISSUE TITLE
에디터 전환 문제

### ISSUE THREAD

**Issue by commania1** [Needlworks/Textcube#1735]
안녕하세요, 새로 업데이트된 텍스트큐브 잘 사용하고 있습니다.
그런데 1.10.1 발표후보 1에서 에디터 전환이 되지 않습니다.

IE와 크롬 모두 HTML에서 TTML로 전환해도 TinyMCE 편집기가 뜨지 않고, 
TTML의 TinyMCE 편집기에서 텍스트큐브 위지윅 에디터로 전환하려고 해도 전환이 가능하지 않습니다.

감사합니다.

**Comment by inureyes** [comment]
일단 1.10.2 로 넘깁니다-

**Comment by inureyes** [comment]
@commania1 글 및 제목이 아예 없는 페이지에서 에디터를 전환하려고 하면 전환이 되지 않는 것을 master 트리에서 확인했습니다.
 * 글 내용이 있는 페이지의 경우 전환이 됩니다.
 * 제목이 있어도 글 내용이 없으면 전환이 되지 않습니다.

디버그 타임!

**Comment by commania1** [comment]
감사합니다 :)

**Comment by inureyes** [comment]
@commania1  별 말씀을! 버그든 개선 요청이든 맘껏 주세요! :+1:
