### ISSUE TITLE
Table name may conflict with keyword in MySQL

### ISSUE THREAD

**Issue by Snack-X** [Needlworks/Textcube#1739]
MySQL에서는 `LINES`가 [Keyword](http://dev.mysql.com/doc/refman/5.7/en/reserved-words.html)로 지정되어 있습니다. 이 때문에 DB Prefix를 공란으로 설정할 경우, 설치 중 `[##_dbPrefix_##]Lines` 테이블을 생성하는 과정에서 해당 테이블 생성에 실패하여 설치 과정에서 에러가 나는 것을 발견했습니다.
DB Prefix를 공란으로 하는 경우는 드문 경우겠지만, 이를 방지할 필요가 있을 것 같습니다. 테이블 명을 바꾼다면 기존 호환성에 문제가 생길 수도 있으니 설치중에 DB Prefix를 필수로 하는 등의 조건이 필요할 것 같습니다.

**Comment by inureyes** [comment]
@Snack-X 기본값이 반드시 들어가도록 설치 프로그램을 수정했습니다. 감사합니다 :+1:
