### ISSUE TITLE
모바일 환경에서 글 펼침 영역이 출력되지 않음

### ISSUE THREAD

**Issue by Snack-X** [Needlworks/Textcube#1778]
의도적인 동작인지 오류인지는 모르겠습니다만, 모바일 환경에서 글 펼침 영역이 정상적으로 출력되지 않고 있습니다.

1.10.5 설치 후 기본 환경에서 테스트 했을 때 문제가 발생합니다.

**Comment by inureyes** [comment]
@Snack-X  그 부분이 아예 출력되지 않는 것이 아니라 닫힌채로 출력되지 않는거죠? 펼쳐진 채로 출력된다면 예전 피처폰 시대에 만든 JS disabled 환경을 위한 레거시의 영향일 것 같고, 아예 안 나온다면 버그겠습니다.

이제 스마트폰 시대라 more/less javascript 도 켜도 별 탈이 생길 것 같지는 않긴 합니다. :)

**Comment by Snack-X** [comment]
@inureyes 이러한 형태로 출력되고 있습니다.

![2015-03-23 6 38 42](https://cloud.githubusercontent.com/assets/1373527/6777313/e4f8b8d0-d18b-11e4-94f7-16ad4c6a81d2.png)

크롬에서 User Agent를 모바일 환경으로 설정한 화면입니다만, 실제 스마트폰 환경에서도 이렇게 출력됩니다.

**Comment by inureyes** [comment]
@Snack-X  네 의도한 동작이 맞긴 한데 환경이 좋아져서 더이상 유지할 필요가 없으므로 데스크탑과 렌더링을 통일하겠습니다. :D
