### ISSUE TITLE
펼침 영역의 Caret 태그가 지워지지 않음

### ISSUE THREAD

**Issue by Snack-X** [Needlworks/Textcube#1779]
이러한 상황이 자주 일어날 거라고 생각하진 않습니다만,

1. 펼침 영역을 만들고
2. HTML 코드 에디터를 열어
3. `[#M_More|Less|Content_M#]` 의 More나 Less 영역에 커서를 놓은 뒤
4. 코드 에디터 창을 닫으면
5. `<span id="CmCaReT"></span>` 가 지워지지 않고 남게됩니다.

이전의 비슷한 이슈들처럼 CodeMirror 플러그인과의 문제인 것 같습니다.

**Comment by inureyes** [comment]
https://github.com/Needlworks/Textcube/issues/1742 이 티켓의 문제가 More/Less에도 나타나는 현상으로 보입니다. 수정하겠습니다! :)
