### ISSUE TITLE
카테고리 선택 시 글 목록 표시 오류

### ISSUE THREAD

**Issue by HNMaru** [Needlworks/Textcube#1783]
블로그 내에서 카테고리를 선택해서 글 목록을 표시하는 경우(글 목록만이나 글 내용과 함께 표시할 경우 모두)에 글 목록이 2중으로 표시가 됩니다.

카테고리를 처음 선택했을 경우에는 아래와 같이 별 문제없이 나옵니다만
![001](https://cloud.githubusercontent.com/assets/11631991/6879421/e2d24e72-d537-11e4-8e5d-445188f3e0a4.jpg)

같은 카테고리를 한 번 더 클릭할 경우에는 아래처럼 글 목록 2중 + 목록 네비가 하나.
![002](https://cloud.githubusercontent.com/assets/11631991/6879424/f892ef5a-d537-11e4-8a64-2646920644e7.jpg)

한 번 더 선택하면 글 목록 + 목록 네비가 2중으로 나옵니다.
![000](https://cloud.githubusercontent.com/assets/11631991/6879410/b4facc4a-d537-11e4-806a-26dbc626471c.jpg)

사용하는 스킨은 기본으로 포함된 Periwinkle 스킨입니다만
제가 손을 댄 부분도 있어서 스킨문제인가 싶어 다른 기본스킨 모두 적용해보았습니다만
결과는 마찬가지였습니다.

1.10.5 버전 기본 상태입니다.

**Comment by inureyes** [comment]
캐시 이름 중복 문제로 보입니다. 수정하겠습니다. :dancer:
