### ISSUE TITLE
블로그 스킨에서 드롭다운 메뉴가 있을 경우 펼쳤다 접으면 사라지는 문제가 있습니다.

### ISSUE THREAD

**Issue by HNMaru** [Needlworks/Textcube#1787]
Periwinkle 스킨에 상단 메뉴 중 하나가 드롭다운으로 구성이 되어있는데
이 드롭다운 메뉴를 한 번 펼쳤다가 접으면 사라져버립니다.
비슷한 구조로 만든 레이아웃도 동일현상이 일어나며
새로고침하면 다시 나타나기는 합니다.

1.10.5랑 1.10.6 rc1 에서 문제 발생합니다.

**Comment by inureyes** [comment]
@HNMaru 혹시 사용하시는 브라우저 버전을 알려주실 수 있을까요? Safari / Firefox / Google Chrome에서는 이 현상이 발견되지 않습니다. (맥에서 테스트했습니다.) 윈도우에서 IE로도 테스트해 보겠습니다.

**Comment by inureyes** [comment]
@lunamoth 혹시 윈도우에서 테스트하실 수 있는 환경이 되시면 테스트 부탁 드립니다 :dancer:

**Comment by inureyes** [comment]
IE11 / Windows 8.1 에서도 이 현상이 발견되지 않습니다 ㅠ_ㅠ

**Comment by HNMaru** [comment]
@inureyes 지금 제 환경인 윈도우 8.1 IE11/Firefox 37.0/Chrome 41.0 에서 테스트시 모두 문제가 발생하네요.. 모바일에서도 마찬가지로 사라집니다..

**Comment by HNMaru** [comment]
@inureyes 제 사이트 문제일 수도 있으니 주소 남겨놓겠습니다.
http://blog.hnmaru.com/ 그리고 #1789 이슈에 관해서 제 사이트에서는 별 문제 없이 작동하고 있습니다.
지금 커버페이지를 메인으로 해놓았으니 한 번 봐주셨으면 합니다.

**Comment by inureyes** [comment]
@HNMaru 사이트에 들어가보니 링크 주신 사이트에서는 저도 재현되네요. 사이트에서 뭔가가 충돌하는 것 같은데 확인이 필요하겠습니다.

**Comment by inureyes** [comment]
@HNMaru 디버그해 보았는데, 드랍다운 메뉴를 연 다음 다시 누르면 해당 li 오브젝트에 style="display:none;" 이 붙어서 사라진 것 처럼 보입니다. 어떤 코드가 해당 명령을 입력하는지는 확실하지 않은데요, lightbox 자바스크립트가 의심됩니다. 한 번 플러그인을 끄시고 확인 부탁 드려요~

**Comment by HNMaru** [comment]
@inureyes 말씀해주신대로 Lightbox 플러그인을 끄는걸로 해결되었습니다. 감사합니다 ^^
