### ISSUE TITLE
1.10.6 RC1 카테고리에서 페이징이 나오지 않는 문제가 있습니다.

### ISSUE THREAD

**Issue by lunamoth** [Needlworks/Textcube#1788]
더링님이 알려주신 버그입니다.

버전 : 1.10.6 RC1

문제 : 카테고리 리스트에서 하단 페이징이 출력되지 않습니다. / 지난 버전에서는 카테고리 하단 페이징이 2개로 출력됐다고 합니다.

관련 URL : http://thering.co.kr/category/%EC%8B%A4%ED%99%94%EA%B4%B4%EB%8B%B4

**Comment by inureyes** [comment]
#1783 의 사이드이펙트로 보입니다. /_\

**Comment by inureyes** [comment]
수정 완료. 확인 부탁 드립니다.

**Comment by lunamoth** [comment]
수정 완료 확인 됐습니다
