### ISSUE TITLE
1.10.6 RC1 커버 페이지를 메인 페이지로 하는 기능이 동작하지 않습니다.

### ISSUE THREAD

**Issue by lunamoth** [Needlworks/Textcube#1789]
더링님이 알려주신 버그입니다.

1.10.6 RC1

커버 페이지를 메인 페이지로 하는 기능이 동작하지 않습니다.

따로 /cover 주소로 접근하면 작동은 한다고 합니다.

**Comment by inureyes** [comment]
관리 패널 로그인하면 나오는 대시보드에서 '캐시 지우기'를 한 후에 확인 부탁 드립니다. 1.10.5에서의 페이지캐시 오류가 반영되고 있는것같아 보입니다. :D

**Comment by lunamoth** [comment]
예 문제 없는듯 싶습니다.
