### ISSUE TITLE
TinyMCE + Markdown 사용 관련 이슈

### ISSUE THREAD

**Issue by initguru** [Needlworks/Textcube#1806]
안녕하세요. 텍스트큐브 1.10.6 신규 사용자입니다.

기본 모드인 TinyMCE+TTML에서 블록 지정 등의 자잘한 오류가 있어, 이번에 Markdown을 사용해보려고 합니다.
TinyMCE 모드에서 Markdown 포매터가 선택은 되는데, 글을 작성 후 블로그 화면을 보게 되면 syntax 포함하여 그대로 텍스트로만 보입니다.
에디터 비활성화가 안되어 plugins 디렉토리에서 제거 후 Markdown을 사용하면 양식이 제대로 보입니다.

따라서 아래 조치가 필요할 듯 합니다.
* TinyMCE 에서 Markdown을 지원하지 않는다면 Markdown 선택 비활성화
* Markdown 선택 시 사용 가능한 에디터 안내 (팝업 등)

GitHub의 Markdown 방식이라면 참 간결하고 유용하겠습니다.

**Comment by inureyes** [comment]
옙 #1727 을 통해 tinyMCE 에서 제대로 된 markdown 지원을 추가하려고 노력 중입니다. 원래 계획은 markdown / html 을 side-by-side로 에디팅 및 프리뷰 지원하는 환경을 구현하는 것인데, 일단 말씀하신 것 처럼 textarea 기반의 markdown authoring 환경부터 마무리를 짓도록 하겠습니다.

**Comment by inureyes** [comment]
TODO : convert <br /> to /r/n when saving.
