### ISSUE TITLE
tinyMCE에서 HTML 수정이 되지 않는 문제

### ISSUE THREAD

**Issue by waltererz** [Needlworks/Textcube#1813]
Textcube 1.10.7 발표후보 1 로 업데이트한 후 문제가 발생하고 있습니다.
tinyMCE에서 HTML을 수정할 때 아래의 오류 메시지가 나타나며, HTML 수정이 되지 않습니다.
Uncaught TypeError: cm.listSelections is not a function [active-line.js:26]
Uncaught TypeError: cm.listSelections is not a function [matchbrackets.js:70]
이미지를 첨부하였습니다. → http://imgur.com/fNRBsCV

------------------------------------------------------------------------------
운영체제: Windows 8.1 Pro
브라우저: Chrome 43.0.2357.65 m

**Comment by inureyes** [comment]
@waltererz 1.10.7의 경우 tinyMCE 에디터의 소스코드 편집은 모달 팝업이 아니라 에디터를 대체하는 형태로 나타납니다. 혹시 에디터를 예전 버전을 사용하고 계신 것이 아닐런지요?

**Comment by waltererz** [comment]
@inureyes 웹브라우저의 캐시를 삭제하니 해결되었습니다. 모달 창이 아니라 편집 창에서 곧바로 HTML 수정이 가능해졌군요... 제가 .htaccess에 Expires 옵션을 1년으로 설정해두어서 캐시된 내용이 그대로 표시되었나봅니다...

**Comment by inureyes** [comment]
@waltererz  :D
