### ISSUE TITLE
TC 1.10.7 RC1의 tinyMCE에서 기본으로 사용하는 문단 태그

### ISSUE THREAD

**Issue by waltererz** [Needlworks/Textcube#1814]
텍스트큐브 1.10.7 RC1으로 업데이트하니 tinyMCE에서 문단 태그로서 p 태그를 사용하고 있었습니다.

Enter 키를 누르면 p 태그가 추가되어, 새로운 문단이 시작되는데, div 태그를 주로 사용하는 저로서는 불편하였습니다. 항상 Shift+Enter를 눌러야 합니다. 저는 글을 작성할 때 각종 박스를 표현하기 위하여 div 태그를 사용합니다.

그래서 기존에 사용해왔던 Enter 키를 누르면 br 태그가 추가되는 옵션을 찾았지만, 이와 같은 옵션이 없는 것 같았습니다.

기본으로 p 태그를 문단 태그로 사용하는 것 뿐만 아니라 문단 태그 없이 br 태그를 삽입하는 옵션이 있었으면 좋겠습니다.

**Comment by inureyes** [comment]
;; br as default.
