### ISSUE TITLE
comment on reply not work

### ISSUE THREAD

**Issue by cheum** [Needlworks/Textcube#1825]
Textcube 1.10.7
When i write reply on comment, reply button is not work. just move top screen as work like href="#" when i click it.
Thank you.

**Comment by inureyes** [comment]
Let me check this. :+1:

**Comment by inureyes** [comment]
@cheum is your Textcube using external javascript resource option?

**Comment by cheum** [comment]
Yes i did, but turn off this option was still not help.
This is my current config options

ini_set('display_errors', 'off');
$database['server'] = 'localhost';
$database['database'] = '';
$database['username'] = '';
$database['password'] = '';
$database['prefix'] = 'tc_';
$service['type'] = 'single';
$service['domain'] = 'cheum.net';
$service['path'] = '';
$service['timeout'] = 900;
$service['skin'] = 'periwinkle';
$service['language'] = 'ko';
$service['timezone'] = 'Asia/Seoul';
$service['encoding'] = 'UTF-8';
$serviceURL = 'http://cheum.net';
$service['cookie_prefix'] = '';
$service['pagecache'] = 1;
$service['codecache'] = 0;
$service['skincache'] = 1;
$service['memcached'] = 0;
$service['reader'] = 1;
$service['useNumericRSS'] = 0;
$service['useEncodedURL'] = 0;
$service['externalresources'] = 0;
$service['resourceURL'] = '';
$service['allowBlogVisibilitySetting'] = 1;
$service['requirelogin'] = 0;
$service['flashclipboardpoter'] = 1;
$service['flashuploader'] = 1;
$service['debugmode'] = 0;
$service['debug_session_dump'] = 0;
$service['debug_rewrite_module'] = 0;
$service['favicon_daily_traffic'] = 10;

**Comment by inureyes** [comment]
It seems to related to the model comment popup function. I'll dig it more.

**Comment by inureyes** [comment]
@cheum : can you test 20e772c and tell us a result? We suspect that there are more than one jQuery instance on the page. This patch resolves that problem by limiting the scope.

**Comment by cheum** [comment]
Didn't work. sorry...

**Comment by inureyes** [comment]
@cheum  Some plugins use their own jQuery. The patch above can solve the problem (maybe; ) :-D
