### ISSUE TITLE
tinyMCE 에디터 문자 깨짐현상

### ISSUE THREAD

**Issue by yuti** [Needlworks/Textcube#1830]
<img width="402" alt="screen shot 2015-08-10 at 22 23 43" src="https://cloud.githubusercontent.com/assets/8939330/9172432/8532f7d0-3fae-11e5-96ea-7a63b9e46151.png">
tinyMCE 에디터만 이렇게 뜨네요.
TTMLsupport/plugin.min.js에서 western (windows 1252)을 utf-8로 변경하면 물음표는 사라지지만, 역시 깨져서 출력됩니다.

**Comment by inureyes** [comment]
자바스크립트 인코딩 판별 문제로 보입니다. 강제 지정을 하지 않아서 브라우저 기본으로 파싱되는 듯 합니다. 인코딩 지정을 해서 수정하도록 하겠습니다.
