### ISSUE TITLE
skin.html의 <script>에 자동으로 //<![CDATA[ ~ //]]> 가 추가 되는 것

### ISSUE THREAD

**Issue by waltererz** [Needlworks/Textcube#1831]
![default](https://cloud.githubusercontent.com/assets/7940031/9245728/62feab2a-41e1-11e5-9cdc-03846159252b.PNG)

XHTML에서는 필요한 주석이라고 알고 있습니다.
그런데 요즘 많이 사용되고 있는 HTML5과 웹브라우저에서는 필요 없습니다.

새로운 스킨도 HTML5 기반으로 제작되고 있는데, 다음 버전에서는 //<![CDATA[ ~ //]]> 이 부분이 자동으로 생성되는 것이 없어지면 어떨지 생각이 듭니다. 이 주석이 생기면 자바스크립트를 일렬로 나열하는 것이 불가능해집니다. ㅠㅠ 스크립트가 주석처리...

**Comment by inureyes** [comment]
2.0에선 날려버리겠습니다~!

**Comment by waltererz** [comment]
@inureyes 감사합니다!
