### ISSUE TITLE
Inserting unicode emoji in article and saving removes all html content after the character

### ISSUE THREAD

**Issue by zvuc** [Needlworks/Textcube#1840]
Reproduce
1. Write text.
2. Insert unicode emoji (😂)
3. Write text after the emoji character.
4. Save post.
5. Go into editor again
6. Text after and including the emoji character is gone.

**Comment by inureyes** [comment]
I tested and found that emoji is replaced with ????, and contents are still preserved. Tested with Chrome 51 (MacOSX)

**Comment by inureyes** [comment]
@zvuc I checked and found the reason that broken emoji sujpport is originated from weak support of 4-byte emoji in MySQL. Please change the table collation from utf8 to utf8md4 and it should work fine. :)
