### ISSUE TITLE
textcube.org connection error

### ISSUE THREAD

**Issue by min050820** [Needlworks/Textcube#1862]
textcube.org 에 접속이 안됩니다.
접속시 "Connection error : - " 라고만 뜨고 그 외 아무것도 뜨지 않습니다. (아무런 HTML 태그도 없습니다)

파이어폭스 모바일 및 데스크톱으로 실험 해 봤습니다.

**Comment by inureyes** [comment]
Solved (long time ago.. Sorry!)
