### ISSUE TITLE
php.ini의 safe_mode=on일 때 Eolin.PHP.Core.php의 오류

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#374]
php.ini의 safe_mode를 on으로 설정할 경우 Eolin.PHP.Core.php의 702 라인에서 오류가 발생함.
에러 내용은 다음과 같음.

-----

Warning: putenv() [function.putenv]: Safe Mode warning: Cannot set environment variable 'TZ' - it's not in the allowed list in /Users/graphittie/Projects/Tattertools/sandbox/single/components/Eolin.PHP.Core.php on line 702

<ul><li>이슈 등록시간: 2007-04-25T20:21:22</li>
<li>마지막 수정시간: 2007-05-21T03:53:06</li></ul>

<table class="trac-migrated-comments">
<tr><th style="text-align:left">Comment 1 by inureyes at 2007-04-26T03:36:01</th></tr>
<tr><td>
골치 아프군요. safe mode에서는 php가 서버의 환경 변수를 임의로 변경할 때 php.ini에서 지정한 변수만을 변경할 수 있습니다. 운영하는 서버이면 TZ를 추가하면 끝이지만, 설치하는 경우에는 safe_mode_allowed_env_vars 를 변경할 수가 없습니다.
[[BR]]
현재의 타임존 변경 부분의 workaround 를 찾아야 할 듯.
</td></tr>
</table>

**Comment by inureyes** [comment]
Now this is not a problem (with > 5.3)
