### ISSUE TITLE
DB 추상화

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#512]
DB 추상화를 통해 설치환경의 범위를 넓힌다...

<ul><li>이슈 등록시간: 2007-08-11T15:23:35</li>
<li>마지막 수정시간: 2007-08-11T15:25:24</li></ul>

<table class="trac-migrated-comments">
<tr><th style="text-align:left">Comment 1 by graphittie at 2007-08-11T15:24:14</th></tr>
<tr><td>
누구한테 assign하나 고민하다가 결국은 교주님... 흑흑... -0-
</td></tr>
<tr><th style="text-align:left">Comment 2 by graphittie at 2007-08-11T15:25:24</th></tr>
<tr><td>
PostSQL, mSQL, Cubrid 등, 무료 기반의 DB 지원을 해야하지 않을까 합니다.
</td></tr>
</table>

**Comment by inureyes** [comment]
* Completed with new context / data model. :)
