### ISSUE TITLE
https 인증

### ISSUE THREAD

**Issue by textcube-dev** [Needlworks/Textcube#939]
# 개요 
* 필요한 부분에 https및 기타 인증루틴을 강화하는 처리를 합니다.

<ul><li>이슈 등록시간: 2008-04-21T02:15:50</li>
<li>마지막 수정시간: 2009-10-08T13:52:19</li></ul>

<table class="trac-migrated-comments">
</table>

**Comment by zvuc** [comment]
최근에 CloudFlare에서 HTTP/2 지원을 시작해서, 이걸 사용해보려고 기존에 안 쓰던 Flexible SSL설정으로 돌리고 http:// 로 접속하는 걸 전부 https://로 돌리는 작업을 했는데요, 스킨에 있는 URL은 전부 protocol-relative 한 //로 수정하니 일단 다 잘 되긴 하더라구요. 이미지는 http여도 mixed content로 일단 로딩은 되는데, 혹시 이런것들도 블로그 관리패널의 설정으로 http:// 대신 https로 일괄 출력되도록 바꿀 수 있는 방법이 있을까요?

**Comment by inureyes** [comment]
@zvuc 지금 구현에서는 기본 도메인이 https 면 전부 자동으로 https 로 바뀌어야 합니다. 확인해 보아야겠네요. 혹시 config.php 안의 내용에 serviceURL 등이 //로 되어 있는지 한 번 확인 부탁 드립니다.

**Comment by zvuc** [comment]
아, 서비스 관리 설정에서 서비스 리소스 경로를 https://로 하니까 적용이 된것같습니다 ㅎㅎ 감사합니다!

**Comment by inureyes** [comment]
@zvuc  :+1:
